### ISSUE TITLE
OMG!

### ISSUE THREAD

**Issue by ingconti** [da4do0/Server_parking#2]
private int translateAscii(int mess) {
        switch (mess) {
            case 49 -> {
                return 1;
            }
            case 50 -> {
                return 2;
            }
            case 51 -> {
                return 3;
            }
            case 52 -> {
                return 4;
            }
            default -> {
                return -1;
            }
        }
    }

BUT SIMPLY 

mess = mes - 48???

**Comment by da4do0** [comment]
omg, emh i fixing right now
